ALTER TABLE VENDAS CHANGE ID_CLIENTE ID_CLIENTE BIGINT;
ALTER TABLE VENDAS CHANGE ID_VENDEDOR ID_VENDEDOR BIGINT;
ALTER TABLE VENDAS ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PESSOA (ID);
ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES PESSOA (ID);
