DROP TRIGGER TG_RELATORIO_COMPRAS;
DROP TRIGGER TG_RELATORIO_COMPRAS_DELETE;
DROP TRIGGER TG_BAIXA_ESTOQUE;
DROP TRIGGER TG_RETORNA_ESTOQUE;
DROP TRIGGER TG_RELATORIO_VENDAS;
DROP TRIGGER TG_RELATORIO_VENDAS_DELETE;

DROP TABLE RELATORIO;