CREATE TABLE IF NOT EXISTS ITEM_VENDA (
  ID              INTEGER AUTO_INCREMENT,
  ID_VENDA        BIGINT,
  ID_CARRO        BIGINT,
  QTDE            INTEGER,
  VLR_UNITARIO    NUMERIC (15,2),
  DESCONTO        NUMERIC (15,2),
  VLR_TOTAL       NUMERIC (15,2),
PRIMARY KEY (ID)
);