ALTER TABLE COMPRAS ADD COLUMN ID_FORNECEDOR BIGINT;
ALTER TABLE COMPRAS ADD COLUMN VLR_TOTAL NUMERIC (15,2);
ALTER TABLE COMPRAS ADD CONSTRAINT FK_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES PESSOA(ID);
