DROP TRIGGER TG_RELATORIO_COMPRAS;
DROP TRIGGER TG_RELATORIO_VENDAS;

DELIMITER |
CREATE TRIGGER TG_RELATORIO_COMPRAS AFTER INSERT
ON COMPRAS
FOR EACH ROW
BEGIN
INSERT INTO RELATORIO (TIPO, VLR, DATA) VALUES ('C', NEW.VLR_TOTAL, NEW.DATA_COMPRA);
END;
|
DELIMITER;

DELIMITER |
CREATE TRIGGER TG_RELATORIO_VENDAS AFTER INSERT
ON VENDAS
FOR EACH ROW
BEGIN
INSERT INTO RELATORIO (TIPO, VLR, DATA) VALUES ('V', NEW.VLR_TOTAL, NEW.DATA_VENDA);
END;
|
DELIMITER;